### ISSUE TITLE
explicit_done and onload

### ISSUE THREAD

**Issue by darobin** [darobin/test-harness-tutorial#6]
From Dominik Röttsches

"""
After just losing a lot of hair and nerve here, figuring out why testharnessreport wouldn't print anything, I found out that my tests had already completed and testharness.js decided the action was already over and 0 tests were scheduled. The reason is: I needed an explict_done: true and called setup() in my onload function - but testharness.js adds its own onload handler and if you hadn't set explicit_done:true before that, it just ends.

Maybe you can add a paragraph in your tutorial about this in the explict_done or in the setup paragraphs. It should be in bold red letters "If you use explicit_done: true - set it before onload". 
"""

**Comment by drott** [comment]
Thanks for logging this one.

**Comment by darobin** [comment]
By the way if you have a code example of how to do it wrong/right, I'll be happy to include it!

**Comment by drott** [comment]
If I'll find the time, I can try to provide sth like that. Basically, just put <pre>setup( { explicit_done: true })</pre> inline somewhere in the header and do not call it at any point after the onload handler, e.g. not in your own onload handler function.
